#!/usr/bin/zsh -e

usage() {
  echo "usage: heracles-init"
  exit 1
}

if [ "$#" -ne 0 ]; then
  usage
fi

if [ -e .heracles ]; then
  >&2 echo "[error] vault appears to be initialized"
  exit 1
fi

git init

touch .heracles
git add .heracles

echo "*unlocked*" > .gitignore
git add .gitignore

git commit --message "Initialized vault"

