#!/usr/bin/zsh -e

usage() {
  echo "usage: heracles-init"
  exit 1
}

if [ "$#" -ne 0 ]; then
  usage
fi

SERIAL_FILE="SERIAL"
if [ -e $SERIAL_FILE ]; then
  >&2 echo "[error] vault appears to be initialized"
  exit 1
fi

git init

SERIAL=0
printf "%06d\n" $SERIAL > $SERIAL_FILE

git add $SERIAL_FILE
git commit --message "Initialized vault"

